/**
 * The API surfaces related to gui objects in the game.
 *
 * A note on the documentation: This package is autogenerated and documentation might be missing.
 */
package com.ldtteam.jvoxelizer.client.gui;